version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      args:
        - API_URL=/api
    container_name: city-bike-journeys-frontend

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - frontend

  backend:
    build: ./backend
    environment:
      - PORT=3000
      - POSTGRES_URI=postgresql://db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PW=example
    container_name: city-bike-journeys-backend
    depends_on:
      - db
  
  db:
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    container_name: city-bike-journeys-db