version: '3.8'

services:
  server: 
    image: express-server
    build:
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    environment:
      - POSTGRES_URL=postgresql://example@db:5432
    container_name: journey-back-dev

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    container_name: journey-db
    ports:
      - 5432:5432