version: '3.8'

services:
  db:
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    container_name: journey-db
    ports:
      - 8000:5432

  db-test:
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    container_name: journey-db-test
    ports:
      - 8001:5432